spring:
  application:
    name: poc
  datasource:
    url: r2dbc:oracle://exampledb.turkcell.com:1521/exampledb.service.name
    username: amaris
    password: amaris
  profiles:
      active: dev
  jpa:
      generate-ddl: true
      hibernate.dd-auto: update
          
logging:
  level:
    org: 
      springframework: INFO 
    com:
      turkcell: INFO


